### ISSUE TITLE
Profling tools

### ISSUE THREAD

**Issue by codecnotsupported** [Cevelop/Issues#31]
### Expected Behavior & Actual Behavior

![c e_tb1](https://user-images.githubusercontent.com/2294209/27010316-d81b556a-4ea1-11e7-84d6-44661b1596cf.png)

Cevelop seems to be missing some profiling tools, those tools seem to be part of LinuxTools https://eclipse.org/linuxtools/

I didn't manage to get any profiling tools to work, whether that is my fault or Cevelop's lack of support is inconclusive.

### Cevelop Version, Operating System and Compiler
Cevelop 1.7.1, Linux, g++-7

**Comment by misto** [comment]
Hi, we don't have the linux tools bundled with Cevelop, but you can just install them: http://wiki.eclipse.org/Linux_Tools_Project/PluginInstallHelp

**Comment by tcorbat** [comment]
Addition to Mirko's reply:
There is a dependency from the Linux Tools to the C/C++ Autotools support. Please install that before trying to install the Linux Tools, otherwise you will not be able to install them due to a missing dependency.

The CDT Autotools can be found on the Eclipse Release Update Site: http://download.eclipse.org/releases/neon

**Comment by codecnotsupported** [comment]
Eh, thanks @misto and @tcorbat, The absence of C/C++ Autotools seemed to be the issue.
