### ISSUE TITLE
Errors with Includator Static Include Analysis Status

### ISSUE THREAD

**Issue by rmerriam** [Cevelop/Issues#32]
Installed Cevelop 1.7.1. Created a new set of project directories separate from a new workspace. The projects were from Eclipse Mars.3. Cannot understand these errors.

Ubuntu 14.04, gcc 4.9,

`Includator Static Include Analysis Status
Warnings:
/home/rmerriam/development/ROS/cevelop_ws/src/mystic_mars
File 'cstdalign' has unknown file type and was thus ignored. If it is a C / C++ file, please add 'cstdalign' to the 'File Types' list under 'C/C++ General->File Types' in 'Eclipse Preferences' or in the project's 'Project Properties'.
File 'signature_of_eigen3_matrix_library' has unknown file type and was thus ignored. If it is a C / C++ file, please add 'signature_of_eigen3_matrix_library' to the 'File Types' list under 'C/C++ General->File Types' in 'Eclipse Preferences' or in the project's 'Project Properties'.
Errors:
ext/slist
CDT does not consider the file 'ext/slist' as a C or C++ source or header file. Please add 'slist' to the 'File Types' list under 'C/C++ General->File Types' in 'Eclipse Preferences' or the project's 'Project Properties'.
CDT does not consider the file 'ext/slist' as a C or C++ source or header file. Please add 'slist' to the 'File Types' list under 'C/C++ General->File Types' in 'Eclipse Preferences' or the project's 'Project Properties'.`

**Comment by tcorbat** [comment]
Eclipse CDT requires to know about the content of the files it is asked to parse. Usually it can determine the content type by the sufix, e.g. .cpp, .hpp etc. The files listed don't have such a sufix. Thus CDT is not aware of the content type. It is possible to circumvent this problem by adding them to the `File Types` configuration section in either the workspace preferences or the project properties.
At least add `slist`. However, I've never seen it report a path like `ext/slist`, but that might vanish when adding `slist`. I think the report for `signature_of_eigen3_matrix_library` can be ignored since that file does not contain actual code. 

I hope this helps.
