### ISSUE TITLE
Constinator Wrongly Suggests Adding 'const' to virtual method

### ISSUE THREAD

**Issue by rmerriam** [Cevelop/Issues#36]
The Constinator suggests adding 'const' to this virtual method in a derived class:

`     virtual void process() override;
`

In the base class there is no 'const' and following the suggestion results in compiler errors. The refactoring is also incorrect resulting in:

`     virtual void process() const override override;
`

Cevelop 1.7.1
GCC 4.9
Ubuntu 14.04.5

Note: I'm really interested in using Cevelop to improve my coding, otherwise I'd not bother posting these issues and go back to Mars.3.

**Comment by tcorbat** [comment]
This issue is reported by the analysis with a lower level of confidence. It has a blue marker instead of a green. Such cases that might not be determined for sure whether the declaration should be const can be turned of separately. In the workspace preferences/project properties -> C/C++ -> Code Analysis -> Constificator Problems -> Uncheck "Possibly missing const-qualification"

We'll look into the specific case and see whether we can eliminate this false positive.
However, the duplicate `override` keyword must not occur. It might be a CDT issue though.

**Comment by rmerriam** [comment]
There are a lot of false positives adding 'const' to methods. 
Thanks for mentioning the marker color, I hadn't picked up on it. I think these appear as 'info' rather than 'warning'?

**Comment by tcorbat** [comment]
Yes that's right. Those are "info" markers.
If you have specifc cases with false positives (or negatives) we're interested in knowing about them.

**Comment by fmorgner** [comment]
Fixed in the latest version of the Beta Plug-ins. Constificator should not have reported a "low-confidence" problem in the first place, since the quick-fix resolution results in code that does not compile. Thanks for your report and happy coding!
