### ISSUE TITLE
CUTE constructor codan checker and quick fix partially broken

### ISSUE THREAD

**Issue by PeterSommerlad** [Cevelop/Issues#52]
### Expected Behavior

checker should not create false positive on template class ctor usage of compiling code

### Actual Behavior

```
namespace CT{
template<typename T1 = Warehouse> struct OrderT {
	OrderT(std::string const & whisky, int i) :	what { whisky }, howmany { i } {	}
};//other parts omitted
using Order = OrderT<>;

//in test function also in namespace CT:
	Order const order(TALISKER, 50);
```
No such constructor for type 'CT::OrderT'.

generates from quick fix in class OrderT:
```
template<typename T1 = Warehouse> struct OrderT {
	CT::OrderT(int const & tALISKER, int const & i) {
	}
...
```

### Cevelop Version, Operating System and Compiler

The more we know about your setup, the easier it will be for us to reproduce the problem.

**Comment by Darnor** [comment]
The detection is actually an issue with CDT because it cannot correctly deduce the type for `TALISKER`. There is currently being work done to fix this (See https://git.eclipse.org/r/#/c/112454/) but this sadly won't make it into the next CDT release. As for now it will correctly detect the ctor it if you either use `auto` without `std::string_literals` or explicitly say that it is a `std::string`.

We've updated the code generation to no longer have namespaces as part of their declarator though.
