### ISSUE TITLE
Update to CDT 9.4

### ISSUE THREAD

**Issue by dermojo** [Cevelop/Issues#70]
I'm currently suffering from the following CDT bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=516338
(unique_ptr is broken with GCC 7).

Are there any plans to update/release a new version based on CDT 9.4?

**Comment by tcorbat** [comment]
Our plan is to release Cevelop 1.9.0 within the next three weeks. Usually
we are quicker in adapting to  new CDT releases, but we have some
infrastructural changes that need to be ported to CDT 9.4 first. Then we'll
be able to package the next version of Cevelop.

I hope you can continue working with Cevelop despite the but you mentioned.

On Jan 30, 2018 12:29, "Daniel Evers" <notifications@github.com> wrote:

I'm currently suffering from the following CDT bug:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=516338
(unique_ptr is broken with GCC 7).

Are there any plans to update/release a new version based on CDT 9.4?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Cevelop/Issues/issues/70>, or mute the thread

**Comment by dermojo** [comment]
Thanks for the update. I'll try to keep my coworkers calm :)

(Feel free to close the issue with the release or in advance...)

**Comment by tcorbat** [comment]
Update complete! You should be able to get the new version from our download site. We'll probably create another release soon when CDT 9.4.2 is released. Enjoy the release!
