### ISSUE TITLE
Regular popup "Could not find map entry for @InfoArgument field [nodeName] in CharwarsInfo"

### ISSUE THREAD

**Issue by dermojo** [Cevelop/Issues#90]
### Expected Behavior

No error popups :)

### Actual Behavior

The error message above is popping up in a window somewhat regularly. I cannot reproduce it, but it keeps happening - more or less, depending on the source file I guess.
The log shows multiple of the following entries:
```
!ENTRY org.eclipse.jface 4 2 2019-02-28 12:47:53.596
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
ch.hsr.ifs.iltis.cpp.core.resources.info.InfoException: Could not find map entry for @InfoArgument field [nodeName] in CharwarsInfo 
```

### Cevelop Version, Operating System and Compiler

1.11.1, RHEL7 Linux, GCC 8.2

**Comment by tonisuter** [comment]
Hi Daniel

Thanks for the report. We think that this problem may occur because Cevelop 1.11.1 tries to read error / warning markers that were persisted by the previous version of Cevelop (which used a slightly different format for these markers). The following steps make sure that the old markers are replaced by new ones:

1. In the `Problems` view select all errors and warnings, right-click and select `Delete`.
2. Right-click on the project and select `Run C/C++ Code Analysis`.

I hope this solves the problem. Otherwise please let us know.

Thanks and best regards
Toni

**Comment by dermojo** [comment]
Hi Toni,

Thanks for the quick response. First tests look promising! I'll monitor the problem for a few days and let you know.

Thanks & regards,
Daniel

**Comment by dermojo** [comment]
Looks good, thanks a lot!
